### ISSUE TITLE
[Bug] Fatal Error when executing without argument

### ISSUE THREAD

**Issue by Jonathan-Racaud** [RogueMacro/grill#3]
When running grill without arguments it calls Internal.FatalError because the command is unknown.

![image](https://user-images.githubusercontent.com/4101737/88076890-eb28f500-cb7a-11ea-8ced-ab62b90ccf77.png)

Ran using the default *Debug* configuration.

**Comment by RogueMacro** [comment]
This is because of a bug that it is not display the help message: https://github.com/RogueMacro/grill/pull/4
